var hotels = [
    {
        name: "Four Seasons Hotel Tunis",
        id: 1,
        city: "Tunis",
        address: "1057 La Marsa, Gammarth",
        stars: 5,
        image_url: "https://cf.bstatic.com/images/hotel/max1024x768/163/163641203.jpg",
        description:`Located in La Marsa, the Golden Tulip Carthage Tunis hotel is on Gammarth Bay, overlooking the crystal clear waters of the Gulf of Tunis. Free Wi-Fi is provided throughout.
        All rooms and suites are comfortable and most rooms have a view of the sea or the swimming pool. They have a minibar and a balcony.
        The hotel offers different bars and restaurants with local specialties and international menus. Enjoy also the restoring cabaret with its dancers and orchestra.`,
        single_room:520,
        double_room:740,
    },
    {
        name: "Laico Tunis",
        id: 2,
        city: "Tunis",
        address: "Chabane El Bhouri av. Tunis 1080",
        stars: 5,
        image_url: "https://media-cdn.tripadvisor.com/media/photo-s/15/e9/16/d6/laico-tunis.jpg",
        description:`Strategically located at the heart of the city center, just miles away from the airport as well as many touristic 
        and business attraction, a haven of elegance, an architecture that melts the hearts of all visitors, Laico Hotel – SPA & Conference Center Tunis, 
        allying Business and Leisure is one of the top luxurious hotel in Tunisia.`,
        single_room:410,
        double_room:608,
    },
    {
        name: "The Penthouse Suites Hotel",
        id: 3,
        city: "Tunis",
        address: "Medinat Radhoua av. Ariana",
        stars: 5,
        image_url: "https://image.resabooking.com/images/image_panoramique/Penthouse_Suites_Hotel_2.jpg",
        description:`Strategically located at the heart of the city center, just miles away from the airport as well as many touristic 
        and business attraction, a haven of elegance, an architecture that melts the hearts of all visitors, Laico Hotel – SPA & Conference Center Tunis, 
        allying Business and Leisure is one of the top luxurious hotel in Tunisia.`,
        single_room: 378,
        double_room:430,
    },
    {
        name: "El Mouradi Gammarth",
        id: 4,
        city: "Tunis",
        address: "B.P597 Gammarth، La Marsa 2070",
        stars: 5,
        image_url: "https://image.resabooking.com/images/hotel/El_Mouradi_Gammarth_.jpg",
        description:`Strategically located at the heart of the city center, just miles away from the airport as well as many touristic 
        and business attraction, a haven of elegance, an architecture that melts the hearts of all visitors, Laico Hotel – SPA & Conference Center Tunis, 
        allying Business and Leisure is one of the top luxurious hotel in Tunisia.`,
        single_room:240,
        double_room:310,
    },
    {
        name: "Ramada Plaza Tunis",
        id: 5,
        city: "Tunis",
        address: "Les Cotes De Cathage, Gammarth",
        stars: 5,
        image_url: "https://image.resabooking.com/images/image_panoramique/Ramada_Plaza_Tunis_2.png",
        description:`Strategically located at the heart of the city center, just miles away from the airport as well as many touristic 
        and business attraction, a haven of elegance, an architecture that melts the hearts of all visitors, Laico Hotel – SPA & Conference Center Tunis, 
        allying Business and Leisure is one of the top luxurious hotel in Tunisia.`,
        single_room:370,
        double_room:530,
    },
    {
        name: "Novotel Tunis Mohamed V",
        id: 6,
        city: "Tunis",
        address: "Mohamed V av. Tunis 1002",
        stars: 5,
        image_url: "https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_1300,q_auto,w_2000/itemimages/21/45/2145176_v6.jpeg",
        description:`Strategically located at the heart of the city center, just miles away from the airport as well as many touristic 
        and business attraction, a haven of elegance, an architecture that melts the hearts of all visitors, Laico Hotel – SPA & Conference Center Tunis, 
        allying Business and Leisure is one of the top luxurious hotel in Tunisia.`,
        single_room:350,
        double_room:460,
    },
    {
        name: "Carthage Thalasso Resort",
        id: 7,
        city: "Tunis",
        address: "LES COTES DE CARTHAGE. BP720. Gammarth 2070",
        stars: 5,
        image_url: "https://image.resabooking.com/images/image_panoramique/Carthage_Thalasso_2.png",
        description:`Strategically located at the heart of the city center, just miles away from the airport as well as many touristic 
        and business attraction, a haven of elegance, an architecture that melts the hearts of all visitors, Laico Hotel – SPA & Conference Center Tunis, 
        allying Business and Leisure is one of the top luxurious hotel in Tunisia.`,
        single_room:300,
        double_room:400,
    },
    {
        name: "Golden Tulip Carthage",
        id: 8,
        city: "Tunis",
        address: "Rue de la Republique, La Marsa 2078",
        stars: 5,
        image_url: "https://image.resabooking.com/images/image_panoramique/Golden_Tulip_Carthage_2.png",
        description:`Located in La Marsa, the Golden Tulip Carthage Tunis hotel is on Gammarth Bay, overlooking the crystal clear waters of the Gulf of Tunis. Free Wi-Fi is provided throughout.
        All rooms and suites are comfortable and most rooms have a view of the sea or the swimming pool. They have a minibar and a balcony.
        The hotel offers different bars and restaurants with local specialties and international menus. Enjoy also the restoring cabaret with its dancers and orchestra.
        For your relaxation, the hotel suggests Antonin centre, with the traditional hammam, indoor swimming pool and sauna.`,
        single_room:570,
        double_room:800,
    },
    { name: "Anantara Sahara Tozeur Resort & Villas", 
    id: 9,
    city: "Tozeur",
    stars: 5,
    image_url: "atoz_acc_onebedroompoolvilla_poolview_gallery_1920x1037.jpg",
    description:` A modern fusion of Moorish and Berber architecture, Anantara Tozeur is a true desert sanctuary, among Tunisia resorts, with desert tones and desert views. Enjoy the Saharan sun out on your private terrace, then retreat into spacious, cool interiors.`,
    single_room:"320", 
    double_room:"577", 
    }, 
    { 
    name: "Radisson Blu Palace Resort et Thalasso", 
id: 10, 
city: "Djerba",
stars: 5,
image_url: "Radisson_Blu_Palace_Resort_et_Thalasso_19.jpg (723×500) (resabooking.com)", 
description:` The Radisson Blu Palace Resort & Thalasso, Djerba lies only a short walk away from the white sandy beaches of the Mediterranean Sea. Within a few minutes of the hotel, you'll find a casino, the Djerba Golf Club and a popular market in the town of Souk Houmt. The Djerba-Zarzis International Airport is 20 kilometers away and airport transfer can be arranged. The hotel is home to 4 delicious restaurants, allowing you to sample Italian, Andalusian, seafood and international specialties. For a refreshing cocktail, stop by the lobby or beachside bar.
Conveniently located on the grounds, the deluxe Athénée Thalasso pampers guests with a host of spa and massage treatments.`, 
single_room:"191", 
double_room:"221", 
},
{ name: "Iberostar Mehari Djerba",
 id: 11, 
city: "Djerba",
stars: 4,
image_url: "https://hotels1.cdn.iberostar.com/uploads/image/43747/crops/16:9/1920/image.jpeg", 
description:` Did you know that Homer took Ulysses to rest on the island of Djerba after the Trojan war?… At Iberostar Mehari Djerba you will discover exactly why he chose this place nicknamed the Island of Golden Sand by Gustave Flaubert…
Facing Sidi Akkour beach, Iberostar Mehari Djerba is surrounded by 50,000 square metres of gardens and palm trees. A hotel for all the family that brings you Arabic, Oriental and Mediterranean cuisine, and allows you to simply enjoy the Beach Bar right on the sand. Ensure that the youngsters have a good time at Star Camp and treat yourself to the holistic and well-being offerings of our Aliveness programme, with activities to rejuvenate and reconnect both with your roots and with nature.
The only problem? Like Ulysses, you won’t want to leave!
`, 
single_room:"91", 
double_room:"135", },
{ name: "Concorde Green Park Palace",
id: 12, 
city: "Sousse",
stars: 5,
image_url: "image_resize.php (1060×500) (concorde-tunisia.com)", 
description:` Located near a fine sandy beach and very close to one of the most beautiful 36-hole golf courses in Tunisia and a few minutes away from the marina of Port El Kantaoui - Sousse, Concorde Green Park Palace is opening the doors for you of the majestic and luxury Arabo-Andalusian palace, enthroned in the middle of a 5 ha luxuriant garden where the palm trees stand majestically around the huge swimming pool and the edge of the beach. Adorned by its hanging gardens and extensive lawns, the hotel truly deserves its name.`, 
single_room:"144", 
double_room:"219", },
{ name: "Sousse palace", 
 id: 13, 
city: "Sousse",
address: "30 avenue Habib Bourguiba, 4000, Sousse - Tunisia", 
stars: 5,
image_url: "https://media-cdn.tripadvisor.com/media/photo-s/0d/91/ba/26/sousse-palace.jpg", 
description:` Sousse Palace Hôtel & Spa 5* is a luxury hotel located in the heart of the old town of Sousse, the “Pearl of the Sahel” and one of Tunisia’s most vibrant towns, located just 87 miles from the capital Tunis. The hotel, founded in 1966 and fully renovated in 2016, has direct access to the beach and offers a total of 250 exquisitely decorated rooms which combine design and comfort, the ideal setting for a luxurious stay in Sousse for tourists and business travellers alike.`, 
single_room:"144", 
double_room:"219", },
{ name: "The Sindbad", 
 id: 14, 
city: "Hammamet",
address: "United Nations 8050 Hammamet, Tunisia",
stars: 5,
image_url: "The_Sindbad_.jpg (723×500) (resabooking.com)", 
description:` The Sindbad hotel is located directly on the beach and built in 1966. The hotel had its latest renovation
of public facilities and rooms in 2008/2009/2013. The architectural style is a sober mix between western
and oriental, surrounded by a beautiful and lush garden.`, 
single_room:"190", 
double_room:"250", },
{ name: "Hasdrubal Thalassa et SPA Hammamet",
id: 15, 
city: "Hammamet",
address: "Zone Touristique Yasmine Hammamet B.P. N°04 - 8050 HAMMAMET TUNISIE", 
stars: 5,
image_url: "https://image.resabooking.com/images/image_panoramique/Hasdrubal_Thalassa_et_SPA_Hammamet_2.jpg", 
description:` Along a huge beach of fine sand, HASDRUBAL Yasmine Hammamet is a sumptuous stopover where you will discover the harmonious contrast of the magnitude of the volumes and the intimacy of the different spaces, sculpted by the jets of water and light that animate its architecture, with luxury and refinement to the smallest detail.`, 
single_room:"230", 
double_room:"334", 
},
{ 
name: "Regency Hammamet", 
id: 16, 
city: "Hammamet",
address: "Avenue de la Paix – B.P. 112  8050 Hammamet-Tunisia ", 
stars: 4,
image_url: "https://image.resabooking.com/images/image_panoramique/Regency_Hammamet_2.jpg", 
description: `Completely renovated in 2014, endowed with a unique charm that of a green garden trimmed with palm trees and various plants as well as a magnificent sandy beach to which there is a direct access, Hammamet Regency Hotel provides well-being and relaxation. 
Being one of the largest in the region, our 190 rooms and suites are all fitted with air conditioning and central heating, hairdryer, satellite TV, private bath with separate toilet, balcony or terrace... 
With three restaurants and four bars, Hammamet Regency Hotel provides a choice which guarantees every kind of pleasure. 
Our main restaurant, which has a beautiful terrace overlooking the pool and garden, offers a buffet of diverse local and international cuisine, meeting everyone’s expectations.`, 
single_room:"48", 
double_room:"96", },
{ name: "La Cigale",
id: 17, 
city: "Tabarka",
address: "El Morjene tourist area, 8110 Tabarka, Tunisia", 
stars: 5,
image_url: "la_cigale_5.jpg (723×500) (resabooking.com)", 
description:` Ideally located near the charming historic village of Tabarka, on the superb North-West coastline
of Tunisia, La Cigale Tabarka Thalasso, SPA and Golf is a magic place where refined luxury, traditional hospitality, and lush greenery mix together. A perfect North-African evasion located in the tourist zone of Mourjane, 2 km from the historic downtown and 12 km from Tabarka international airport. The hotel has 248 rooms and suites, five restaurants which offer different menus, five luxurious bars, a Turkish coffee and a large selection of areas for leisure and business.`, 
single_room:"285", 
double_room:"390", },
{ name: "Les Mimosas",
 id: 18, 
city: "Tabarka",
address: "Av Habib Bourguiba, Tabarka", 
stars: 3,
image_url: "https://image.resabooking.com/images/image_panoramique/Les_Mimosas_2.jpg", 
description:`the hotel is surrounded by the most famous ports of tabarka such as the marina of tabarka which is
located at 1.5 km in its surroundings, the port of tabarka which is also at 1.8 km. apart from the ports, there is 
the fort of tabarka which is 2.7 km away, it is surrounded by beautiful beaches.`, 
single_room:"78", 
double_room:"108", },
{
    name: "LTI Mahdia Beach & Aquapark", 
    id: 19, 
    city: "Mahdia",
    address: "Zone Touristique, Mahdia 5100", 
    stars: 4,
    image_url: "https://image.resabooking.com/images/image_panoramique/LTI_Mahdia_Beach_&_Aquapark_2.jpg", 
    description: `On the east coast of Tunisia, a peaceful peninsula emerges with a glorious past and irresistible charm. The city of Mahdia has been the subject of several conquests and was the capital of the Fatimids in the 10th century.`, 
    single_room:"49", 
    double_room:"87", 
},


    {
        name: "La Badira",
        id: 20,
        city: "Hammamet",
        address: "HAMMAMET NORD, Hammamet, Nabeul, 8050",
        stars: 5,
        image_url: "https://www.labadira.com/sites/default/files/Infinity%20Pool%20-%20Vue%20hotel.jpg",
        description:`Located in a unique setting, the hotel La Badira, of modern construction, therefore revisits the spirit of this era and offers infrastructures of exceptional quality: sea view rooms and suites, innovative local cuisine, redesigned by a great chef, as well as tailor-made services and excursions, all powered by the latest technology.`,
        single_room:332,
        double_room:540,
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:``,
        single_room:"",
        double_room:"",
    },
    {
        name: "",
        id: 7,
        city: "",
        address: "",
        stars: 5,
        image_url: "",
        description:`the hotel is surrounded by the most famous ports of tabarka such as the marina of tabarka which is
        located at 1.5 km in its surroundings, the port of tabarka which is also at 1.8 km. apart from the ports, there is 
        the fort of tabarka which is 2.7 km away, it is surrounded by beautiful beaches.`,
        single_room:"",
        double_room:"",
    },
    
    
]

